<?php
/**
 * GroupsV2GroupEditAction
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bungie.Net API
 *
 * These endpoints constitute the functionality exposed by Bungie.net, both for more traditional website functionality and for connectivity to Bungie video games and their related functionality.
 *
 * The version of the OpenAPI document: 2.9.2
 * Contact: support@bungie.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GroupsV2GroupEditAction Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class GroupsV2GroupEditAction implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GroupsV2.GroupEditAction';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'about' => 'string',
        'motto' => 'string',
        'theme' => 'string',
        'avatar_image_index' => 'int',
        'tags' => 'string',
        'is_public' => 'bool',
        'membership_option' => 'int',
        'is_public_topic_admin_only' => 'bool',
        'allow_chat' => 'bool',
        'chat_security' => 'int',
        'callsign' => 'string',
        'locale' => 'string',
        'homepage' => 'int',
        'enable_invitation_messaging_for_admins' => 'bool',
        'default_publicity' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'about' => null,
        'motto' => null,
        'theme' => null,
        'avatar_image_index' => 'int32',
        'tags' => null,
        'is_public' => null,
        'membership_option' => 'int32',
        'is_public_topic_admin_only' => null,
        'allow_chat' => null,
        'chat_security' => 'int32',
        'callsign' => null,
        'locale' => null,
        'homepage' => 'int32',
        'enable_invitation_messaging_for_admins' => null,
        'default_publicity' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'about' => 'about',
        'motto' => 'motto',
        'theme' => 'theme',
        'avatar_image_index' => 'avatarImageIndex',
        'tags' => 'tags',
        'is_public' => 'isPublic',
        'membership_option' => 'membershipOption',
        'is_public_topic_admin_only' => 'isPublicTopicAdminOnly',
        'allow_chat' => 'allowChat',
        'chat_security' => 'chatSecurity',
        'callsign' => 'callsign',
        'locale' => 'locale',
        'homepage' => 'homepage',
        'enable_invitation_messaging_for_admins' => 'enableInvitationMessagingForAdmins',
        'default_publicity' => 'defaultPublicity'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'about' => 'setAbout',
        'motto' => 'setMotto',
        'theme' => 'setTheme',
        'avatar_image_index' => 'setAvatarImageIndex',
        'tags' => 'setTags',
        'is_public' => 'setIsPublic',
        'membership_option' => 'setMembershipOption',
        'is_public_topic_admin_only' => 'setIsPublicTopicAdminOnly',
        'allow_chat' => 'setAllowChat',
        'chat_security' => 'setChatSecurity',
        'callsign' => 'setCallsign',
        'locale' => 'setLocale',
        'homepage' => 'setHomepage',
        'enable_invitation_messaging_for_admins' => 'setEnableInvitationMessagingForAdmins',
        'default_publicity' => 'setDefaultPublicity'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'about' => 'getAbout',
        'motto' => 'getMotto',
        'theme' => 'getTheme',
        'avatar_image_index' => 'getAvatarImageIndex',
        'tags' => 'getTags',
        'is_public' => 'getIsPublic',
        'membership_option' => 'getMembershipOption',
        'is_public_topic_admin_only' => 'getIsPublicTopicAdminOnly',
        'allow_chat' => 'getAllowChat',
        'chat_security' => 'getChatSecurity',
        'callsign' => 'getCallsign',
        'locale' => 'getLocale',
        'homepage' => 'getHomepage',
        'enable_invitation_messaging_for_admins' => 'getEnableInvitationMessagingForAdmins',
        'default_publicity' => 'getDefaultPublicity'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    const MEMBERSHIP_OPTION_0 = 0;
    const MEMBERSHIP_OPTION_1 = 1;
    const MEMBERSHIP_OPTION_2 = 2;
    const CHAT_SECURITY_0 = 0;
    const CHAT_SECURITY_1 = 1;
    const HOMEPAGE_0 = 0;
    const HOMEPAGE_1 = 1;
    const HOMEPAGE_2 = 2;
    const DEFAULT_PUBLICITY_0 = 0;
    const DEFAULT_PUBLICITY_1 = 1;
    const DEFAULT_PUBLICITY_2 = 2;
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getMembershipOptionAllowableValues()
    {
        return [
            self::MEMBERSHIP_OPTION_0,
            self::MEMBERSHIP_OPTION_1,
            self::MEMBERSHIP_OPTION_2,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChatSecurityAllowableValues()
    {
        return [
            self::CHAT_SECURITY_0,
            self::CHAT_SECURITY_1,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getHomepageAllowableValues()
    {
        return [
            self::HOMEPAGE_0,
            self::HOMEPAGE_1,
            self::HOMEPAGE_2,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDefaultPublicityAllowableValues()
    {
        return [
            self::DEFAULT_PUBLICITY_0,
            self::DEFAULT_PUBLICITY_1,
            self::DEFAULT_PUBLICITY_2,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = $data['name'] ?? null;
        $this->container['about'] = $data['about'] ?? null;
        $this->container['motto'] = $data['motto'] ?? null;
        $this->container['theme'] = $data['theme'] ?? null;
        $this->container['avatar_image_index'] = $data['avatar_image_index'] ?? null;
        $this->container['tags'] = $data['tags'] ?? null;
        $this->container['is_public'] = $data['is_public'] ?? null;
        $this->container['membership_option'] = $data['membership_option'] ?? null;
        $this->container['is_public_topic_admin_only'] = $data['is_public_topic_admin_only'] ?? null;
        $this->container['allow_chat'] = $data['allow_chat'] ?? null;
        $this->container['chat_security'] = $data['chat_security'] ?? null;
        $this->container['callsign'] = $data['callsign'] ?? null;
        $this->container['locale'] = $data['locale'] ?? null;
        $this->container['homepage'] = $data['homepage'] ?? null;
        $this->container['enable_invitation_messaging_for_admins'] = $data['enable_invitation_messaging_for_admins'] ?? null;
        $this->container['default_publicity'] = $data['default_publicity'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getMembershipOptionAllowableValues();
        if (!is_null($this->container['membership_option']) && !in_array($this->container['membership_option'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'membership_option', must be one of '%s'",
                $this->container['membership_option'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getChatSecurityAllowableValues();
        if (!is_null($this->container['chat_security']) && !in_array($this->container['chat_security'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'chat_security', must be one of '%s'",
                $this->container['chat_security'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getHomepageAllowableValues();
        if (!is_null($this->container['homepage']) && !in_array($this->container['homepage'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'homepage', must be one of '%s'",
                $this->container['homepage'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getDefaultPublicityAllowableValues();
        if (!is_null($this->container['default_publicity']) && !in_array($this->container['default_publicity'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'default_publicity', must be one of '%s'",
                $this->container['default_publicity'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets about
     *
     * @return string|null
     */
    public function getAbout()
    {
        return $this->container['about'];
    }

    /**
     * Sets about
     *
     * @param string|null $about about
     *
     * @return self
     */
    public function setAbout($about)
    {
        $this->container['about'] = $about;

        return $this;
    }

    /**
     * Gets motto
     *
     * @return string|null
     */
    public function getMotto()
    {
        return $this->container['motto'];
    }

    /**
     * Sets motto
     *
     * @param string|null $motto motto
     *
     * @return self
     */
    public function setMotto($motto)
    {
        $this->container['motto'] = $motto;

        return $this;
    }

    /**
     * Gets theme
     *
     * @return string|null
     */
    public function getTheme()
    {
        return $this->container['theme'];
    }

    /**
     * Sets theme
     *
     * @param string|null $theme theme
     *
     * @return self
     */
    public function setTheme($theme)
    {
        $this->container['theme'] = $theme;

        return $this;
    }

    /**
     * Gets avatar_image_index
     *
     * @return int|null
     */
    public function getAvatarImageIndex()
    {
        return $this->container['avatar_image_index'];
    }

    /**
     * Sets avatar_image_index
     *
     * @param int|null $avatar_image_index avatar_image_index
     *
     * @return self
     */
    public function setAvatarImageIndex($avatar_image_index)
    {
        $this->container['avatar_image_index'] = $avatar_image_index;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets is_public
     *
     * @return bool|null
     */
    public function getIsPublic()
    {
        return $this->container['is_public'];
    }

    /**
     * Sets is_public
     *
     * @param bool|null $is_public is_public
     *
     * @return self
     */
    public function setIsPublic($is_public)
    {
        $this->container['is_public'] = $is_public;

        return $this;
    }

    /**
     * Gets membership_option
     *
     * @return int|null
     */
    public function getMembershipOption()
    {
        return $this->container['membership_option'];
    }

    /**
     * Sets membership_option
     *
     * @param int|null $membership_option membership_option
     *
     * @return self
     */
    public function setMembershipOption($membership_option)
    {
        $allowedValues = $this->getMembershipOptionAllowableValues();
        if (!is_null($membership_option) && !in_array($membership_option, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'membership_option', must be one of '%s'",
                    $membership_option,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['membership_option'] = $membership_option;

        return $this;
    }

    /**
     * Gets is_public_topic_admin_only
     *
     * @return bool|null
     */
    public function getIsPublicTopicAdminOnly()
    {
        return $this->container['is_public_topic_admin_only'];
    }

    /**
     * Sets is_public_topic_admin_only
     *
     * @param bool|null $is_public_topic_admin_only is_public_topic_admin_only
     *
     * @return self
     */
    public function setIsPublicTopicAdminOnly($is_public_topic_admin_only)
    {
        $this->container['is_public_topic_admin_only'] = $is_public_topic_admin_only;

        return $this;
    }

    /**
     * Gets allow_chat
     *
     * @return bool|null
     */
    public function getAllowChat()
    {
        return $this->container['allow_chat'];
    }

    /**
     * Sets allow_chat
     *
     * @param bool|null $allow_chat allow_chat
     *
     * @return self
     */
    public function setAllowChat($allow_chat)
    {
        $this->container['allow_chat'] = $allow_chat;

        return $this;
    }

    /**
     * Gets chat_security
     *
     * @return int|null
     */
    public function getChatSecurity()
    {
        return $this->container['chat_security'];
    }

    /**
     * Sets chat_security
     *
     * @param int|null $chat_security chat_security
     *
     * @return self
     */
    public function setChatSecurity($chat_security)
    {
        $allowedValues = $this->getChatSecurityAllowableValues();
        if (!is_null($chat_security) && !in_array($chat_security, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'chat_security', must be one of '%s'",
                    $chat_security,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['chat_security'] = $chat_security;

        return $this;
    }

    /**
     * Gets callsign
     *
     * @return string|null
     */
    public function getCallsign()
    {
        return $this->container['callsign'];
    }

    /**
     * Sets callsign
     *
     * @param string|null $callsign callsign
     *
     * @return self
     */
    public function setCallsign($callsign)
    {
        $this->container['callsign'] = $callsign;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string|null $locale locale
     *
     * @return self
     */
    public function setLocale($locale)
    {
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets homepage
     *
     * @return int|null
     */
    public function getHomepage()
    {
        return $this->container['homepage'];
    }

    /**
     * Sets homepage
     *
     * @param int|null $homepage homepage
     *
     * @return self
     */
    public function setHomepage($homepage)
    {
        $allowedValues = $this->getHomepageAllowableValues();
        if (!is_null($homepage) && !in_array($homepage, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'homepage', must be one of '%s'",
                    $homepage,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['homepage'] = $homepage;

        return $this;
    }

    /**
     * Gets enable_invitation_messaging_for_admins
     *
     * @return bool|null
     */
    public function getEnableInvitationMessagingForAdmins()
    {
        return $this->container['enable_invitation_messaging_for_admins'];
    }

    /**
     * Sets enable_invitation_messaging_for_admins
     *
     * @param bool|null $enable_invitation_messaging_for_admins enable_invitation_messaging_for_admins
     *
     * @return self
     */
    public function setEnableInvitationMessagingForAdmins($enable_invitation_messaging_for_admins)
    {
        $this->container['enable_invitation_messaging_for_admins'] = $enable_invitation_messaging_for_admins;

        return $this;
    }

    /**
     * Gets default_publicity
     *
     * @return int|null
     */
    public function getDefaultPublicity()
    {
        return $this->container['default_publicity'];
    }

    /**
     * Sets default_publicity
     *
     * @param int|null $default_publicity default_publicity
     *
     * @return self
     */
    public function setDefaultPublicity($default_publicity)
    {
        $allowedValues = $this->getDefaultPublicityAllowableValues();
        if (!is_null($default_publicity) && !in_array($default_publicity, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'default_publicity', must be one of '%s'",
                    $default_publicity,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['default_publicity'] = $default_publicity;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


